### ISSUE TITLE
Plugin is not listed under hardware

### ISSUE THREAD

**Issue by bwbboot** [tuk90/RemehaHome-Domoticz#1]
I don't see any error messages in Domoticz log. But the plugin is not listed under hardware.  Domoticz version 2024.1
asyncio and aiohttp libraries are installed.

Any ideas what to check?

<img width="678" alt="Screenshot 2024-01-07 at 22 04 27" src="https://github.com/tuk90/RemehaHome-Domoticz/assets/31098984/3df94e99-9ddc-4100-b2c0-ee1a9076e581">
<img width="1135" alt="Screenshot 2024-01-07 at 22 05 03" src="https://github.com/tuk90/RemehaHome-Domoticz/assets/31098984/cf32a296-ff59-4296-a884-7e23cabbe5c9">

**Comment by tuk90** [comment]
The issue is that I forgot to change the name of th plugin to plugin.py. Will do so soon
