### ISSUE TITLE
Plug in still working?

### ISSUE THREAD

**Issue by Arjensmailbox** [tuk90/RemehaHome-Domoticz#23]
Hi, I installed this plug in on my Domoticz server. It is not working. Does this plug still work? I recall Remeha changed their platform mid 2024? Has the API changed?

**Comment by tuk90** [comment]
It is still working, do you get an error?

**Comment by Arjensmailbox** [comment]
It is not appearing as a options in the selection box in the hardware tab

**Comment by Arjensmailbox** [comment]
I used the steps as described in your post. I checked on python and version. That is available. I dot not use any other external plu ins.

**Comment by tuk90** [comment]
Did you restart Domoticz?

**Comment by Arjensmailbox** [comment]
yep, I restarted with the command line and also by a new power up. One question: when installing I first did the gitclone command in the domoticz home folder. Saw the flaw and then later used the command in the plugins folder. Could that be the reason? How can I uninstall it all and retry?

**Comment by tuk90** [comment]
Installing it in the plugin folder should be sufficient, are you running Domoticz via Docker?

**Comment by tuk90** [comment]
Ok, does anything show up in de the error log cause it should work

**Comment by Arjensmailbox** [comment]
<img width="847" alt="image" src="https://github.com/user-attachments/assets/018603cd-a44b-46fb-b6dc-734702dc13f9">
this error indeed

**Comment by Arjensmailbox** [comment]
ha.. seems to be empty indeed: 
<img width="572" alt="image" src="https://github.com/user-attachments/assets/0c3dcf81-4dee-45c1-bfa8-6ddbafd2a6a9">

**Comment by Arjensmailbox** [comment]
thnks. Solved. I deleted and re-installed it. It now is working great. A big thankyou for all the help :-)
